### ISSUE TITLE
hideShow 模式时BUG，最后一个会显示到第一个去

### ISSUE THREAD

**Issue by iamsophie** [ifelsend/IfelsendCarousel#9]
你的展示案例里也是这样，刚加载的时候那个星空图显示在第一，然后才开始正常轮播。
我发现在js代码中 hideshow模式里的代码注释才正常从第一个图显示。
你可以多刷一下你的案例展示页面，第一个和第二个案例总是  最后一张星空图先出现。

//li.css('position','absolute');  hideshow 63行代码，我注释了一下。显示正常。怎么解决我也不会哈我是小白

**Comment by naodai** [comment]
很高兴你提issue，也很抱歉，现在才处理。
缺失有这个问题，不能通过注释63行代码来解决，要不第一个图片停留的时间会是 播放speed * 2 
已解决。
